services:

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: smart_hostel_db
    restart: always

    environment:
      MYSQL_DATABASE: smart_hostel
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: hostel_user
      MYSQL_PASSWORD: hostel_password

    ports:
      - "3307:3306"

    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: smart_hostel_backend
    restart: always

    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: smart_hostel
      MYSQL_USER: hostel_user
      MYSQL_PASSWORD: hostel_password
      JWT_SECRET: super_secret_university_smart_hostel_jwt_key_2026

    ports:
      - "8080:8080"

    depends_on:
      db:
        condition: service_healthy

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: smart_hostel_frontend
    restart: always

    ports:
      - "3000:80"

    depends_on:
      - backend

volumes:
  db_data:
